spring:
  application:
    name: product-api
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${DATASOURCE_URL:localhost}:3306/product-api
    username: ${DATASOURCE_USER:root}
    password: ${DATASOURCE_PASSWORD:password}
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration